// <auto-generated />
using BacktestingEngine.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BacktestingEngine.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260227151057_CreateBinanceKlinesTable")]
    partial class CreateBinanceKlinesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BacktestingEngine.Entity.KlineEntity", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("text")
                        .HasColumnName("symbol");

                    b.Property<string>("Interval")
                        .HasColumnType("text")
                        .HasColumnName("interval");

                    b.Property<long>("OpenTimeMs")
                        .HasColumnType("bigint")
                        .HasColumnName("open_time_ms");

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("close");

                    b.Property<long>("CloseTimeMs")
                        .HasColumnType("bigint")
                        .HasColumnName("close_time_ms");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("high");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("low");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("open");

                    b.Property<decimal>("QuoteAssetVol")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("quote_asset_vol");

                    b.Property<decimal>("TakerBuyBase")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("taker_buy_base");

                    b.Property<decimal>("TakerBuyQuote")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("taker_buy_quote");

                    b.Property<long>("TradesCount")
                        .HasColumnType("bigint")
                        .HasColumnName("trades_count");

                    b.Property<decimal>("Volume")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("volume");

                    b.HasKey("Symbol", "Interval", "OpenTimeMs");

                    b.ToTable("binance_klines", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
